---
- hosts: all
  become: yes
  remote_user: vagrant

  vars:
    running: false

  tasks:
    - name: Check python version
      shell: python3 --version
      register: python_version

    - debug: var=python_version.stdout

    - name: Stop squid proxy server.
      service: name=squid state=stopped
      when: running

    - name: Install squid proxy
      command: "sudo apt install squid"
      register: output
      changed_when: "'squid is already the newest version' not in output.stdout"

    - name: Check if the word computer exists in a text
      command: "cat /tmp/output1.txt"
      register: output 
      failed_when: "'computer' in output.stdout"